### ISSUE TITLE
Show processed document

### ISSUE THREAD

**Issue by jonnius** [jonnius/camera-scanner#18]
The backend has a document store that handles documents by a unique ID. The frontend somehow needs to handle those IDs to communicate with the backend.

**Comment by cibersheep** [comment]
Processed documents as pdf, I guess, right?

**Comment by jonnius** [comment]
The processed images are still images. I would only create a PDF to export the result bundled (if the user chooses to)

**Comment by jonnius** [comment]
Fixed by d74cdf9057f3baf29fb6bea175f7bec057a485c6
