### ISSUE TITLE
Load cached session on startup

### ISSUE THREAD

**Issue by jonnius** [jonnius/camera-scanner#21]
maybe this should be optional?

**Comment by cibersheep** [comment]
I would say: last unfinished project load on start, finished projects don't

**Comment by jonnius** [comment]
How do you define a finished project? Is a project finished if the user has exported the result? And if he took another picture afterwards?

**Comment by jonnius** [comment]
Btw. restoring the cache works by just invoking [ImageProcessing.restoreCache()](https://github.com/jonnius/camera-scanner/blob/master/plugins/ImageProcessing/ImageProcessing.h#L21).

**Comment by cibersheep** [comment]
> How do you define a finished project? Is a project finished if the user has exported the result? And if he took another picture afterwards?

Interesting. We need to think about it

**Comment by jonnius** [comment]
I made the app reload previous sessions: https://github.com/jonnius/camera-scanner/blob/master/qml/Main.qml#L34

I think, if we come up with a definition of finishing a session, we might simply delete the cache. This would be the same as a "New Project" Button, that I'd like to see...
